import random
import json
from sqlalchemy.orm import Session
from database import SessionLocal, Product, init_db, engine
from sqlalchemy import text

# Categories and their specific items/vendors
CATEGORIES = {
    "Marine Engineering": {
        "items": ["Diesel Engine 500HP", "Propeller Shaft", "Hydraulic Steering Pump", "Fuel Filter", "Water Separator", "Exhaust Manifold", "Impeller Kit", "Transmission Gearbox", "Bow Thruster", "Stabilizer Fin"],
        "vendors": ["engineering@marine-supply.com", "parts@diesel-experts.com"]
    },
    "Hull & Deck": {
        "items": ["Marine Grade Plywood", "Fiberglass Resin", "Gelcoat White", "Teak Decking Plank", "Stainless Steel Cleat", "Anchor Chain", "Windlass", "Hatch Cover", "Portlight", "Antifouling Paint"],
        "vendors": ["sales@hull-deck.com", "materials@boat-builders.com"]
    },
    "Interior & Furniture": {
        "items": ["Leather Sofa", "Teak Table", "Cabin Mattress", "LED Ceiling Light", "Galley Stove", "Refrigerator 12V", "Marine Toilet", "Shower Mixer", "Curtain Fabric", "Carpet Roll"],
        "vendors": ["interiors@luxury-yachts.com", "decor@marine-living.com"]
    },
    "Electronics & Navigation": {
        "items": ["GPS Chartplotter", "Radar Dome", "VHF Radio", "Autopilot System", "Depth Sounder", "Fishfinder", "Satellite Phone", "Marine Battery", "Inverter 2000W", "Solar Panel"],
        "vendors": ["sales@marine-electronics.com", "tech@nav-systems.com"]
    },
    "Safety Equipment": {
        "items": ["Life Jacket", "Life Raft", "Flare Kit", "Fire Extinguisher", "First Aid Kit", "EPIRB", "Bilge Pump", "Searchlight", "Fog Horn", "Safety Harness"],
        "vendors": ["safety@sea-safe.com", "supplies@rescue-gear.com"]
    },
    "Deck Hardware": {
        "items": ["Winch", "Pulley Block", "Shackle", "Turnbuckle", "Rope 10mm", "Fender", "Boat Hook", "Ladder", "Bimini Top", "Canvas Cover"],
        "vendors": ["hardware@deck-pro.com", "rigging@sail-supply.com"]
    }
}

def generate_products(n=1000):
    products = []
    used_ids = set()
    
    for i in range(n):
        category = random.choice(list(CATEGORIES.keys()))
        base_item = random.choice(CATEGORIES[category]["items"])
        
        # Create variations
        item_name = f"{base_item} - Type {random.choice(['A', 'B', 'C'])} {random.randint(100, 999)}"
        description = f"High quality {base_item.lower()} for marine use. Specification {random.randint(1, 10)}."
        price = round(random.uniform(50, 10000), 2)
        
        # Ensure unique ID
        while True:
            d365_id = f"ITEM-{random.randint(10000, 99999)}"
            if d365_id not in used_ids:
                used_ids.add(d365_id)
                break
        
        # Mock embedding (all zeros for now as we don't want to call OpenAI 1000 times in this script)
        # In a real scenario, you'd batch generate these.
        embedding = [0.0] * 1536 
        
        products.append({
            "name": item_name,
            "description": description,
            "price": price,
            "d365_id": d365_id,
            "category": category,
            "embedding": embedding
        })
    return products

def update_vendor_emails():
    vendor_data = {}
    for cat, data in CATEGORIES.items():
        vendor_data[cat.lower()] = data["vendors"]
    
    with open("vendor_emails.json", "w") as f:
        json.dump(vendor_data, f, indent=2)
    print("Updated vendor_emails.json")

def main():
    print("Initializing Database...")
    init_db()
    
    # Add column if not exists (Hack for SQLite/Dev)
    # SQLAlchemy init_db won't update existing tables.
    # We'll try to execute an ALTER TABLE, ignoring error if it exists.
    with engine.connect() as conn:
        try:
            conn.execute(text("ALTER TABLE products ADD COLUMN category VARCHAR"))
            print("Added category column.")
        except Exception as e:
            print(f"Column might already exist: {e}")

    print("Generating 1000 products...")
    data = generate_products(1000)
    
    session = SessionLocal()
    try:
        # Clear existing products to avoid duplicates
        print("Clearing existing products...")
        session.query(Product).delete()
        session.commit()
        
        print("Inserting products...")
        for item in data:
            # id and last_updated are auto-generated by the database
            p = Product(
                name=item["name"],
                description=item["description"],
                price=item["price"],
                d365_id=item["d365_id"],
                category=item["category"],
                embedding=item["embedding"]
            )
            session.add(p)
        
        session.commit()
        print("Successfully inserted 1000 products.")
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f"Error: {e}")
        session.rollback()
    finally:
        session.close()

    update_vendor_emails()

if __name__ == "__main__":
    main()
